# DATA CLEANING

In [ ]:
import pandas as pd 
shipment = pd.read_json("shipments.json")
warehouse = pd.read_json("warehouses.json")
cost = pd.read_csv("costs.csv")
cstaff = pd.read_csv("courier_staff.csv")
route = pd.read_csv("routes.csv")
shiptrack = pd.read_csv("shipment_tracking.csv")

In [5]:
shipment

,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
0,dc84cc15,2025-06-12,North Dawnfort,Ginafort,43.52,b554e6a4,Cancelled,None
1,ca536e73,2025-06-27,North Williamchester,Christinechester,19.31,9b44d9ca,Cancelled,None
2,704fa19e,2025-09-09,New Colleen,West Jared,27.97,f8c3e908,Delivered,2025-09-13
3,aad8a598,2025-07-25,South Ashleystad,Jonestown,18.74,0de3fc1b,Cancelled,None
4,e120d4ba,2026-01-06,Darinton,West Jared,39.30,44def2f4,In Transit,None
...,...,...,...,...,...,...,...,...
69995,33f9c844,2025-08-09,West Jared,South Brianside,6.66,09470953,Cancelled,None
69996,6ca403d1,2025-09-05,Kimfort,East Johnshire,16.78,353f1b39,Cancelled,None
69997,59a42fb4,2025-05-29,Hollyshire,Port Sandrachester,6.97,acb241ba,Cancelled,None
69998,3cfb7692,2026-02-18,South Ashleystad,New Colleen,49.57,409aec25,Pending,None
69999,f212e1c9,2025-11-14,Tiffanyton,North Christopherstad,33.21,d1370c82,In Transit,None

In [6]:
shipment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shipment_id    70000 non-null  object
 1   order_date     70000 non-null  object
 2   origin         70000 non-null  object
 3   destination    70000 non-null  object
 4   weight         70000 non-null  float64
 5   courier_id     70000 non-null  object
 6   status         70000 non-null  object
 7   delivery_date  17336 non-null  object
dtypes: float64(1), object(7)
memory usage: 4.3+ MB

In [9]:
shipment.isnull().sum()

shipment_id          0
order_date           0
origin               0
destination          0
weight               0
courier_id           0
status               0
delivery_date    52664
dtype: int64

In [10]:
shipment.isnull().sum() / len(shipment) * 100

shipment_id       0.000000
order_date        0.000000
origin            0.000000
destination       0.000000
weight            0.000000
courier_id        0.000000
status            0.000000
delivery_date    75.234286
dtype: float64

In [17]:
shipment['delivery_date'] = pd.to_datetime(shipment['delivery_date'])
shipment['order_date'] = pd.to_datetime(shipment['order_date'])
shipment.dtypes

shipment_id              object
order_date       datetime64[ns]
origin                   object
destination              object
weight                  float64
courier_id               object
status                   object
delivery_date    datetime64[ns]
dtype: object

In [18]:
shipment.duplicated().sum()

np.int64(0)

In [ ]:
shipment[shipment.duplicated(subset="shipment_id", keep=False)] # checks duplicate columns based on shipment_id

In [46]:
shipment.nunique()

shipment_id      69999
order_date         343
origin              50
destination         50
weight            4951
courier_id        1000
status               4
delivery_date      372
dtype: int64

In [19]:
shipment.to_csv("cleaned_shipment.csv", index=False)

In [21]:
warehouse

   warehouse_id                   city state  capacity
0      647a65d8      North Claudiatown    SC      9821
1      8bdbd012             East David    MT      1138
2      cfcbd086           North Justin    ND      6019
3      3bff4497     Port Sandrachester    CT      3300
4      6767e7a4   North Williamchester    SD      6822
5      fb4f0c1e    North Christianside    WI      1419
6      0647f147           North Arthur    OH      5716
7      fde209a7             Davidshire    MT      3014
8      48885907        South Brianside    WI      8819
9      eb497b1e       Christinechester    WI      7387
10     7caf8d4a           Andersonfurt    NC      3229
11     0f74ba8c          East Victoria    VA      7146
12     41b6192b          Port Kimberly    ID      6291
13     da7f8abf    West Timothychester    OH      4759
14     21a4e02c               Darinton    MA      2467
15     85c9673b            Port Ronald    AR      4498
16     9805fcb9            West Wesley    WV      3101
17     c0bb59a2       South Ashleystad    VT      7304
18     260917ca             Carolmouth    HI      3151
19     951758e8                Kimfort    OH      7926
20     b84c93ef           Robertsburgh    MI      5182
21     f3eba9d9  North Christopherstad    PA      1418
22     3d9c3505              New Jesse    CA      7331
23     696538cc       North Trevorbury    NV      6966
24     f5de23cd             South Ryan    NH      4454
25     badfd592             Pamelabury    CO      6722
26     445b5ce6            Brookeburgh    OK      3315
27     7aec3044              Jonestown    CT      6817
28     f49c722a             Tiffanyton    WV      9343
29     58df4cbf      New Patriciashire    MT      1820
30     131d4feb             West Jared    NM      9265
31     e0fe2c38       South Katiemouth    MS      6218
32     74ba985d             South John    ID      1533
33     b4622995         East Johnshire    CA      2080
34     029f2908        New Jeremyshire    HI      9549
35     6f108806        South Johnhaven    OK      1428
36     1fd957e1               Ginafort    OR      4365
37     2a1bebcd           Heathermouth    GA      8698
38     ce02458e         North Dawnfort    AK      1657
39     6581a28b       South Jacqueline    ID      7545
40     725027b4          South Raymond    SC      8378
41     89c71b15           Port Heather    NV      1360
42     29b6d374              Adammouth    CT      7976
43     c26205f3           Port Barbara    CT      3814
44     82b42412           Jasonchester    RI      4897
45     e3a2d775            Shannonview    GU      9915
46     280d966c       West Tarachester    NH      6219
47     6ee4f2f0             Hollyshire    VI      9963
48     e25788e6            New Colleen    ME      1795
49     ade45415             Mooreshire    VT      4894

In [31]:
warehouse.info()
warehouse.isnull().sum()
warehouse.isnull().sum() / len(warehouse) * 100
warehouse.duplicated().sum()
warehouse.to_csv("cleaned_warehouse.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   warehouse_id  50 non-null     object
 1   city          50 non-null     object
 2   state         50 non-null     object
 3   capacity      50 non-null     int64
dtypes: int64(1), object(3)
memory usage: 1.7+ KB

In [32]:
cost

      shipment_id  fuel_cost  labor_cost  misc_cost
0        dc84cc15      61.08       27.24      20.75
1        ca536e73      13.74       65.13      17.63
2        704fa19e      72.68       39.47      16.84
3        aad8a598      53.69       23.23      33.16
4        e120d4ba      90.24      107.29      14.73
...           ...        ...         ...        ...
69995    33f9c844      79.98       77.36      15.16
69996    6ca403d1      53.00       95.18      36.47
69997    59a42fb4      46.60       34.45      30.81
69998    3cfb7692      23.68       26.66      12.96
69999    f212e1c9      66.42       93.76      41.10

[70000 rows x 4 columns]

In [ ]:
cost.info()
cost.isnull().sum()
cost.isnull().sum() / len(cost) * 100
cost.duplicated().sum()
cost.to_csv("cleaned_cost.csv", index=False)

In [33]:
cstaff

    courier_id                name  rating vehicle_type
0     7bc57152        Justin Flynn     4.8          Van
1     87cafee3       Sherry Conrad     3.2        Truck
2     53cc593b          Joanna Liu     4.0          Car
3     c482832b        Samantha Lee     4.9          Car
4     a217d894       Carrie Santos     3.9          Van
..         ...                 ...     ...          ...
995   1bafc418     Andrea Robinson     3.9          Car
996   55f3ed49  Benjamin Middleton     3.8          Van
997   60912cf1    Michele Mcknight     4.5          Car
998   1199b2f9     Johnny Johnston     4.7        Truck
999   78434baa       Melissa Weber     3.0          Van

[1000 rows x 4 columns]

In [35]:
cstaff.info()
cstaff.isnull().sum()
cstaff.isnull().sum() / len(cstaff) * 100
cstaff.duplicated().sum()
cstaff.to_csv("cleaned_cstaff.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   courier_id    1000 non-null   object
 1   name          1000 non-null   object
 2   rating        1000 non-null   float64
 3   vehicle_type  1000 non-null   object
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

In [36]:
cstaff

    courier_id                name  rating vehicle_type
0     7bc57152        Justin Flynn     4.8          Van
1     87cafee3       Sherry Conrad     3.2        Truck
2     53cc593b          Joanna Liu     4.0          Car
3     c482832b        Samantha Lee     4.9          Car
4     a217d894       Carrie Santos     3.9          Van
..         ...                 ...     ...          ...
995   1bafc418     Andrea Robinson     3.9          Car
996   55f3ed49  Benjamin Middleton     3.8          Van
997   60912cf1    Michele Mcknight     4.5          Car
998   1199b2f9     Johnny Johnston     4.7        Truck
999   78434baa       Melissa Weber     3.0          Van

[1000 rows x 4 columns]

In [38]:
cstaff.info()
cstaff.isnull().sum()
cstaff.isnull().sum() / len(cstaff) * 100
cstaff.duplicated().sum()
cstaff.to_csv("cleaned_cstaff.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   courier_id    1000 non-null   object
 1   name          1000 non-null   object
 2   rating        1000 non-null   float64
 3   vehicle_type  1000 non-null   object
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

In [39]:
route

,route_id,origin,destination,distance_km,avg_time_hours
0,fe423f38,East Victoria,South Raymond,1016.50,44.2
1,080ff620,Mooreshire,Davidshire,58.30,45.3
2,aa6e4a5f,Mooreshire,South Raymond,977.98,42.4
3,3aa7af93,Kimfort,East Johnshire,691.84,35.7
4,39913248,Tiffanyton,East David,1836.43,24.4
...,...,...,...,...,...
495,1f571fff,Mooreshire,Kimfort,1137.08,13.6
496,23d6ca93,Jonestown,East Johnshire,833.28,22.8
497,7e163bb8,West Jared,North Claudiatown,370.47,24.2
498,b76d73ec,North Christopherstad,Jasonchester,1886.07,28.7
499,26a5a0b9,New Jesse,Port Kimberly,1682.91,43.4

In [41]:
route.info()
route.isnull().sum()
route.isnull().sum() / len(route) * 100
route.duplicated().sum()
route.to_csv("cleaned_route.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   route_id        500 non-null    object
 1   origin          500 non-null    object
 2   destination     500 non-null    object
 3   distance_km     500 non-null    float64
 4   avg_time_hours  500 non-null    float64
dtypes: float64(2), object(3)
memory usage: 19.7+ KB

In [42]:
shiptrack

        tracking_id shipment_id        status            timestamp
0                 1    dc84cc15  Order Placed  2025-06-12 02:00:00
1                 2    dc84cc15     Cancelled  2025-06-15 00:00:00
2                 3    ca536e73  Order Placed  2025-06-27 02:00:00
3                 4    ca536e73     Cancelled  2025-06-28 00:00:00
4                 5    704fa19e  Order Placed  2025-09-09 03:00:00
...             ...         ...           ...                  ...
209565       209566    3cfb7692  Order Placed  2026-02-18 04:00:00
209566       209567    3cfb7692     Picked Up  2026-02-20 00:00:00
209567       209568    f212e1c9  Order Placed  2025-11-14 01:00:00
209568       209569    f212e1c9     Picked Up  2025-11-16 00:00:00
209569       209570    f212e1c9    In Transit  2025-11-18 00:00:00

[209570 rows x 4 columns]

In [43]:
shiptrack.info()
shiptrack.isnull().sum()
shiptrack.isnull().sum() / len(shiptrack) * 100
shiptrack.duplicated().sum()
shiptrack.to_csv("cleaned_shiptrack.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209570 entries, 0 to 209569
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   tracking_id  209570 non-null  int64
 1   shipment_id  209570 non-null  object
 2   status       209570 non-null  object
 3   timestamp    209570 non-null  object
dtypes: int64(1), object(3)
memory usage: 6.4+ MB

# SQL

In [ ]:
CREATE SCHEMA `logistics_project_1` ;


USE logistics_project_1;

-- 1. Courier Staff
CREATE TABLE IF NOT EXISTS courier_staff (
    courier_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    rating DECIMAL(3,1),
    vehicle_type VARCHAR(50)
);

-- 2. Shipments (depends on courier_staff)
CREATE TABLE IF NOT EXISTS shipments (
    shipment_id VARCHAR(50) PRIMARY KEY,
    order_date DATE NOT NULL,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    courier_id VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    delivery_date DATE NULL,
    CONSTRAINT fk_courier
        FOREIGN KEY (courier_id)
        REFERENCES courier_staff(courier_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- 3. Shipment Tracking (depends on shipments)
CREATE TABLE IF NOT EXISTS shipment_tracking (
    tracking_id INT AUTO_INCREMENT PRIMARY KEY,
    shipment_id VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    timestamp DATETIME NOT NULL,
    CONSTRAINT fk_shipment_tracking
        FOREIGN KEY (shipment_id)
        REFERENCES shipments(shipment_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- 4. Costs (depends on shipments)
CREATE TABLE IF NOT EXISTS costs (
    shipment_id VARCHAR(50) PRIMARY KEY,
    fuel_cost DECIMAL(15,2) NOT NULL DEFAULT 0,
    labor_cost DECIMAL(15,2) NOT NULL DEFAULT 0,
    misc_cost DECIMAL(15,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_costs_shipment
        FOREIGN KEY (shipment_id)
        REFERENCES shipments(shipment_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- 5. Routes
CREATE TABLE IF NOT EXISTS routes (
    route_id VARCHAR(50) PRIMARY KEY,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    distance_km DECIMAL(10,2) NOT NULL,
    avg_time_hours DECIMAL(5,2) NOT NULL
);

-- 6. Warehouses
CREATE TABLE IF NOT EXISTS warehouses (
    warehouse_id VARCHAR(50) PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL,
    capacity INT NOT NULL
);

In [ ]:
USE logistics_project_1;

SELECT * FROM shipments;
SELECT * FROM costs;
SELECT * FROM courier_staff;
SELECT * FROM routes;
SELECT * FROM shipment_tracking;
SELECT * FROM warehouses;

# ETL

In [3]:
shipments_df = pd.read_csv("cleaned_shipment.csv")
shipments_df

,shipment_id,order_date,origin,destination,weight,courier_id,status,delivery_date
0,dc84cc15,2025-06-12,North Dawnfort,Ginafort,43.52,b554e6a4,Cancelled,NaN
1,ca536e73,2025-06-27,North Williamchester,Christinechester,19.31,9b44d9ca,Cancelled,NaN
2,704fa19e,2025-09-09,New Colleen,West Jared,27.97,f8c3e908,Delivered,2025-09-13
3,aad8a598,2025-07-25,South Ashleystad,Jonestown,18.74,0de3fc1b,Cancelled,NaN
4,e120d4ba,2026-01-06,Darinton,West Jared,39.30,44def2f4,In Transit,NaN
...,...,...,...,...,...,...,...,...
69995,33f9c844,2025-08-09,West Jared,South Brianside,6.66,09470953,Cancelled,NaN
69996,6ca403d1,2025-09-05,Kimfort,East Johnshire,16.78,353f1b39,Cancelled,NaN
69997,59a42fb4,2025-05-29,Hollyshire,Port Sandrachester,6.97,acb241ba,Cancelled,NaN
69998,3cfb7692,2026-02-18,South Ashleystad,New Colleen,49.57,409aec25,Pending,NaN
69999,f212e1c9,2025-11-14,Tiffanyton,North Christopherstad,33.21,d1370c82,In Transit,NaN

In [ ]:
shipments_df[shipments_df.duplicated(subset="shipment_id", keep=False)]


# Choosing the best record per shipment_id in shipments_df

# shipment_id | order_date | origin | destination | courier_id | status
# c2c0ddd0      2026-01-31   A        B            X           Cancelled
# c2c0ddd0      2025-04-09   C        D            Y           Delivered

# Row 8106 is better than row 8105 because it has a delivery date, while row 8105 has a null delivery date. So we will keep row 8106 and drop row 8105.

In [ ]:
cost_df = pd.read_csv("cleaned_cost.csv")
cost_df

In [ ]:
cost_df[cost_df.duplicated(subset="shipment_id", keep=False)] # duplicate shipment_id in cost_df

In [ ]:
# Aggregate the costs and Keeps all cost information

costs_df = cost_df.groupby("shipment_id", as_index=False).sum()

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus


# Database connection

password = quote_plus("Alys@003!")
engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/logistics_project_1"
)


# Load CSVs

shipments_df = pd.read_csv("cleaned_shipment.csv")
cstaff_df = pd.read_csv("cleaned_cstaff.csv")
shiptrack_df = pd.read_csv("cleaned_shiptrack.csv")
costs_df = pd.read_csv("cleaned_cost.csv")
routes_df = pd.read_csv("cleaned_route.csv")
warehouses_df = pd.read_csv("cleaned_warehouse.csv")


# Push to MySQL function

def push_to_mysql(df, table_name):
    try:
        df.to_sql(table_name, engine, if_exists="append", index=False)
        print(f"✅ {table_name} successfully inserted.")
    except Exception as e:
        print(f"❌ Error inserting {table_name}: {e}")


# Push tables in dependency order

push_to_mysql(cstaff_df, "courier_staff")      # couriers first
push_to_mysql(shipments_df, "shipments")      # shipments depend on couriers
push_to_mysql(shiptrack_df, "shipment_tracking")  # shipment_tracking depends on shipments
push_to_mysql(costs_df, "costs")              # costs depend on shipments
push_to_mysql(routes_df, "routes")            # independent
push_to_mysql(warehouses_df, "warehouses")    # independent

Removed 1 duplicate shipments
Removed 0 invalid shipment_tracking rows
Removed 1 duplicate/invalid costs rows
✅ courier_staff successfully inserted.
✅ shipments successfully inserted.
✅ shipment_tracking successfully inserted.
✅ costs successfully inserted.
✅ routes successfully inserted.
✅ warehouses successfully inserted.

# STREAMLIT

In [ ]:
import streamlit as st
import pandas as pd
import plotly.express as px
from sqlalchemy import create_engine
from urllib.parse import quote_plus


# Database Connection

password = quote_plus("Alys@003!")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost/logistics_project_1")

@st.cache_data(ttl=300)
def load_data():
    shipments = pd.read_sql("SELECT * FROM shipments", engine)
    tracking = pd.read_sql("SELECT * FROM shipment_tracking", engine)
    costs = pd.read_sql("SELECT * FROM costs", engine)
    couriers = pd.read_sql("SELECT * FROM courier_staff", engine)
    routes = pd.read_sql("SELECT * FROM routes", engine)
    warehouses = pd.read_sql("SELECT * FROM warehouses", engine)
    return shipments, tracking, costs, couriers, routes, warehouses

shipments, tracking, costs, couriers, routes, warehouses = load_data()

st.set_page_config(page_title="Logistics Dashboard", layout="wide")
st.title("🚚 Logistics Intelligence Dashboard")


# A. Shipment Search & Filtering

st.sidebar.header("🔎 Shipment Filters")
status_filter = st.sidebar.multiselect("Status", shipments["status"].unique())
origin_filter = st.sidebar.multiselect("Origin", shipments["origin"].unique())
destination_filter = st.sidebar.multiselect("Destination", shipments["destination"].unique())
courier_filter = st.sidebar.multiselect("Courier", couriers["name"].unique())
shipment_id_filter = st.sidebar.text_input("Shipment ID")
date_range = st.sidebar.date_input("Order Date Range",
                                   [shipments["order_date"].min(), shipments["order_date"].max()])

filtered = shipments.copy()
if status_filter:
    filtered = filtered[filtered["status"].isin(status_filter)]
if origin_filter:
    filtered = filtered[filtered["origin"].isin(origin_filter)]
if destination_filter:
    filtered = filtered[filtered["destination"].isin(destination_filter)]
if courier_filter:
    valid_couriers = couriers[couriers["name"].isin(courier_filter)]["courier_id"]
    filtered = filtered[filtered["courier_id"].isin(valid_couriers)]
if shipment_id_filter:
    filtered = filtered[filtered["shipment_id"].str.contains(shipment_id_filter)]
if date_range:
    filtered = filtered[
        (pd.to_datetime(filtered["order_date"]) >= pd.to_datetime(date_range[0])) &
        (pd.to_datetime(filtered["order_date"]) <= pd.to_datetime(date_range[1]))
    ]

st.subheader("Filtered Shipments")
st.dataframe(filtered)


# B. Operational KPIs

st.subheader("📊 Operational KPIs")
total_shipments = len(shipments)
delivered_pct = (shipments["status"] == "Delivered").mean() * 100
cancelled_pct = (shipments["status"] == "Cancelled").mean() * 100
avg_delivery_time = (pd.to_datetime(shipments["delivery_date"]) - pd.to_datetime(shipments["order_date"])).dt.days.mean()
costs["total_cost"] = costs["fuel_cost"] + costs["labor_cost"] + costs["misc_cost"]
total_cost = costs["total_cost"].sum()

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Shipments", total_shipments)
col2.metric("Delivered %", f"{delivered_pct:.2f}%")
col3.metric("Cancelled %", f"{cancelled_pct:.2f}%")
col4.metric("Avg Delivery Time (days)", f"{avg_delivery_time:.2f}")
col5.metric("Total Operational Cost", f"${total_cost:,.2f}")



st.success("📊 Logistics Dashboard Loaded Successfully!")